add curl in container and retrieve data from weather api
safwaneben/weather pull request #2
Opened 2022-08-17 17:31 UTC by safwaneben

2022-08-21 13:37 UTC, FRANCISAnas requested changes
J'ai laissé quelques retours qu'il faut prendre en compte 😄

2022-08-21 13:37 UTC, FRANCISAnas commented on docker-compose.yml
> +          dockerfile: Dockerfile
```suggestion
        build:
          context: ./apicaller
          dockerfile: Dockerfile
```
```suggestion
        build: ./apicaller
```

2022-08-21 13:37 UTC, FRANCISAnas commented on docker-compose.yml
> +          dockerfile: Dockerfile
```suggestion
        build:
          context: ./dataparser
          dockerfile: Dockerfile
```
```suggestion
        build: ./dataparser
```

2022-08-21 13:37 UTC, FRANCISAnas commented on docker-compose.yml
> +          dockerfile: Dockerfile
```suggestion
        build:
          context: ./predictionservice
          dockerfile: Dockerfile
```
```suggestion
        build: ./predictionservice
```

2022-08-21 13:37 UTC, FRANCISAnas commented on docker-compose.yml
> +          dockerfile: Dockerfile
```suggestion
        build:
          context: ./visualizerservice
          dockerfile: Dockerfile
```
```suggestion
        build: ./visualizerservice
```

2022-08-21 13:37 UTC, FRANCISAnas commented on docker-compose.yml
> +            - 8081:8081
Pourquoi tu as rajouté `ports:` pour chaque image dans le docker-compose et tu as  aussi rajouté la command `EXPOSE` dans les dockerfile., normalement on met soit l'un soit l'autre, là ça devient redendunt.
Bien sûr tu dois tester ça quand tu as supprimé ces arguments pour voir si ça marche toujours 😉

2022-08-21 13:37 UTC, FRANCISAnas commented on predictionservice/Dockerfile
> +EXPOSE 8083
Redendent avec le docker-compose ? 🤔

2022-08-21 13:37 UTC, FRANCISAnas commented on visualizerservice/Dockerfile
> +EXPOSE 8084
Redendent avec le docker-compose ? 🤔

2022-08-21 13:37 UTC, FRANCISAnas commented on dataparser/Dockerfile
> +EXPOSE 8082
Redendent avec le docker-compose ? 🤔

2022-08-21 13:37 UTC, FRANCISAnas commented on apicaller/Dockerfile
> +EXPOSE 8081
OK 😉

2022-09-08 17:19 UTC, safwaneben commented on docker-compose.yml
> +            - 8081:8081
fait

2022-09-08 17:26 UTC, FRANCISAnas approved these changes
OK 👍🏽

2022-09-08 17:26 UTC, merged